name: Unittests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:

    ## We do not install doxygen, as it is disabled in the CMakeLists.txt by default.
    #- name: install doxygen Linux
    #  if: matrix.os == 'ubuntu-latest'
    #  run: |
    #      sudo apt-get install doxygen
    #
    #- name: install doxygen Mac
    #  if: matrix.os == 'macos-latest'
    #  run: |
    #        brew install doxygen
    #
    #- name: install doxygen Windows
    #  if: matrix.os == 'windows-latest'
    #  run: |
    #        choco install --yes doxygen.install


    - uses: actions/checkout@v4
    - name: Configure
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: |
        cmake --build build --config Debug

    - name: Test Windows
      if: matrix.os == 'windows-latest'
      run: |
        ./build/Debug/run_libfs_tests.exe

    - name: Test Linux and Mac OS
      if: matrix.os != 'windows-latest'
      run: |
        ./build/run_libfs_tests

    - name: Build with clang under Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -S. -Bbuild_clang -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
        cmake --build build_clang --config Debug
